### ISSUE TITLE
TextSearchOperator is expecting SearchPath but we don't have the option to send that value as parameter

### ISSUE THREAD

**Issue by silambarasan** [mongodb-developer/getting-started-search-java#1] opened 2023-12-16 03:03 UTC
@erikhatcher , Can you please help me with the example to pass the value to this below method,
![image](https://github.com/mongodb-developer/getting-started-search-java/assets/273296/4b2a91b3-5f2e-4613-a7e4-58d53cd73a6f)

Do you think the parameter to be changed from `SearchPath` to `FieldSearchPath` to pass the parameter to this method like this,
`SearchOperator.of(SearchOperator.text(SearchPath.fieldPath(fieldName), fieldValue));`

Compilation Error : `The method text(SearchPath, String) in the type SearchOperator is not applicable for the arguments (FieldSearchPath, Object)`

Please help me on this.

**Comment by erikhatcher** [comment] 2024-01-09 22:46
@silambarasan apologies for the belated reply (I admittedly had not been paying attention to notifications from this repo).

Does the following construct work for you?  I think it's pretty close to what you are aiming for?

```SearchOperator operator = text(SearchPath.fieldPath("title"),"query");```

**Comment by erikhatcher** [comment] 2024-01-12 14:43
I will close this ticket, @silambarasan - but please re-open if there's still an issue with the code in this repo. For a broader code issue. If the issue is with the Java driver itself, their repo and issue tracker is here: https://github.com/mongodb/mongo-java-driver

**Closed as completed by erikhatcher** 2024-01-12 14:43 UTC
Labels: question
